# Pipeline for Databricks workspace import

trigger:
  branches:
    include:
    - master

stages:
- stage: "dev"
  displayName: "Development"
  dependsOn: []
  pool:
    vmImage: "ubuntu-latest"
  variables:
    - group: databricks_cli

  jobs:
    - job: SyncWorkspace2Dev
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: "3.8"
            architecture: "x64"

        - task: ShellScript@2
          inputs:
            scriptPath: scripts/databricks-cli-config.sh
            args: "$(databricks_host) $(databricks_token)"
          displayName: "Install and configure the Databricks CLI"

        - task: ShellScript@2
          inputs:
            scriptPath: scripts/databricks-deploy-run.sh
            args: "cicd-example"
          displayName: "Deploy and run notebooks"
